; Script generated by the Inno Setup Script Wizard.

#define MyAppName "Assistente"
#define MyAppVersion "0.10"
#define MyAppPublisher "MAURINSOFT"
#define MyAppURL "http://maurinsoft.com.br"
#define MyAppExeName "assistente.exe"
#define MyInstallExeName "setup_assistente_0010"

[Setup]
AppId={{25A25326-C619-4F25-B473-8916AF42FCD1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=D:\projetos\maurinsoft\Assistente\bin\
OutputBaseFilename={#MyInstallExeName}
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Types]
Name: "ASSISTENTE"; Description: {cm:T_ASSISTENTE}

[Components]
Name: "Assistente"; Description: "Arquivos da ASSISTENTE"; Types: ASSISTENTE;

[CustomMessages]
T_ASSISTENTE=ASSISTENTE
TD_ASSISTENTE=Install ASSISTENTE 

[Files]
; Executável principal
Source: "D:\projetos\maurinsoft\ASSISTENTE\src\assistente.exe"; DestDir: "{app}"; Flags: ignoreversion




[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppExeName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
