unit main;
{$mode objfpc}{$H+}
interface
uses Classes,SysUtils,Forms,Controls,Graphics,Dialogs,ExtCtrls,StdCtrls,Buttons,LCLType,GifAnim,chatgpt,setmain,frmconfig,jarvis_api,agent_manager,reception_core,aiagent_memorymap,aiagent_flowevents,voice_input_bridge,aiaudio,aicontinuouslistener;
type
 Tfrmmain=class(TForm)
  pnlRoot,pnlHeader,pnlConteudo,pnlAvatar,pnlEntrada:TPanel; lblTitulo,lblStatus,lblAssistente:TLabel; btConfig:TSpeedButton; GifAvatar:TGifAnim; memResposta:TMemo; edPergunta:TEdit; btEnviar:TButton;
  procedure FormCreate(Sender:TObject);procedure FormDestroy(Sender:TObject);procedure FormShow(Sender:TObject);procedure btConfigClick(Sender:TObject);procedure btEnviarClick(Sender:TObject);procedure edPerguntaKeyDown(Sender:TObject;var Key:Word;Shift:TShiftState);
 private
  FAssistantManager:TAssistantManager;FJarvisClient:TJarvisAPIClient;FSpeechJob:TReceptionJob;FVoiceInput:TVoiceInputBridge;FAudioInput:TAIAudioInput;FContinuousListener:TAIContinuousListener;FMemoryMap:TAIAgentMemoryMap;FMemoryItem:TAIAgentMemoryMapItem;FHistoryFile,FCurrentUserText:string;FAguardandoResposta:Boolean;
  procedure AplicarConfiguracao;procedure CarregarAvatarEstatico;procedure InicializarMemoria;procedure SalvarMemoria;procedure EnviarPergunta;procedure ProcessarEntrada(const ATexto:string);procedure VoiceText(Sender:TObject;const AText:string);procedure VoiceState(Sender:TObject;const AState:string);procedure SpeechReady(Sender:TObject;const AFileName:string);procedure ListenerState(Sender:TObject;AState:TAIListenerState);procedure IniciarEscuta;procedure PausarEscuta;procedure RetomarEscuta;procedure FalarResposta(const ATexto:string);procedure SetEstado(const ATexto:string;AOcupado:Boolean);procedure OnAgentStateChange(Sender:TObject;AState:TAgentState;const ADescription:string);procedure OnAgentComplete(Sender:TObject;const AResponseText,AProvider:string;ASuccess:Boolean);
 public property AssistantManager:TAssistantManager read FAssistantManager;property VoiceInput:TVoiceInputBridge read FVoiceInput;
 end;
var frmmain:Tfrmmain;
implementation
{$R *.lfm}
procedure Tfrmmain.FormCreate(Sender:TObject);
begin FAguardandoResposta:=False;FSpeechJob:=nil;FMemoryItem:=nil;if FSetMain=nil then FSetMain:=TSetMain.Create;FSetMain.CarregaContexto;FJarvisClient:=TJarvisAPIClient.Create(Self);FAssistantManager:=TAssistantManager.Create(Self);FAssistantManager.JarvisClient:=FJarvisClient;FAssistantManager.OnStateChange:=@OnAgentStateChange;FAssistantManager.OnComplete:=@OnAgentComplete;FMemoryMap:=TAIAgentMemoryMap.Create(Self);InicializarMemoria;FVoiceInput:=TVoiceInputBridge.Create(Self);FVoiceInput.OnText:=@VoiceText;FVoiceInput.OnState:=@VoiceState;FAudioInput:=TAIAudioInput.Create(Self);FContinuousListener:=TAIContinuousListener.Create(Self);FContinuousListener.AudioInput:=FAudioInput;FContinuousListener.OnSpeechReady:=@SpeechReady;FContinuousListener.OnStateChange:=@ListenerState;AplicarConfiguracao;CarregarAvatarEstatico;SetEstado('Pronto para conversar',False);end;
procedure Tfrmmain.FormDestroy(Sender:TObject);begin if Assigned(FContinuousListener) then FContinuousListener.Stop;if Assigned(FVoiceInput) then FVoiceInput.Cancel;SalvarMemoria;if Assigned(FSpeechJob) then begin FSpeechJob.Cancel;FreeAndNil(FSpeechJob);end;end;
procedure Tfrmmain.FormShow(Sender:TObject);begin edPergunta.Text:='';IniciarEscuta;edPergunta.SetFocus;end;
procedure Tfrmmain.IniciarEscuta;begin if not FSetMain.ContinuousListening then Exit;FAudioInput.InputSource:=asMic;FAudioInput.SampleRate:=FSetMain.AudioSampleRate;FAudioInput.Channels:=FSetMain.AudioChannels;FAudioInput.DurationLimit:=0;FContinuousListener.VoiceThreshold:=FSetMain.VoiceThreshold;FContinuousListener.SilenceTimeoutMs:=FSetMain.SilenceTimeoutMs;FContinuousListener.MinSpeechMs:=FSetMain.MinSpeechMs;FContinuousListener.MaxSpeechMs:=FSetMain.MaxSpeechMs;FContinuousListener.EchoSuppressionEnabled:=FSetMain.EchoSuppressionEnabled;FContinuousListener.SelfAudioCorrelationThreshold:=FSetMain.SelfAudioCorrelationThreshold;FContinuousListener.Start;end;
procedure Tfrmmain.PausarEscuta;begin if Assigned(FContinuousListener) and FContinuousListener.Enabled then FContinuousListener.Pause;end;
procedure Tfrmmain.RetomarEscuta;begin if Assigned(FContinuousListener) and FContinuousListener.Enabled then FContinuousListener.Resume;end;
procedure Tfrmmain.SpeechReady(Sender:TObject;const AFileName:string);begin PausarEscuta;FVoiceInput.TranscribeWav(AFileName);end;
procedure Tfrmmain.ListenerState(Sender:TObject;AState:TAIListenerState);begin if FAguardandoResposta then Exit;case AState of lsListening:lblStatus.Caption:='Ouvindo...';lsSpeech:lblStatus.Caption:='Escutando fala...';lsSilence:lblStatus.Caption:='Aguardando fim da fala...';lsPaused:lblStatus.Caption:='Microfone pausado';lsError:lblStatus.Caption:='Erro no microfone';end;end;
procedure Tfrmmain.VoiceText(Sender:TObject;const AText:string);begin ProcessarEntrada(AText);end;
procedure Tfrmmain.VoiceState(Sender:TObject;const AState:string);begin if not FAguardandoResposta then lblStatus.Caption:=AState;end;
procedure Tfrmmain.InicializarMemoria;var B:string;begin B:=IncludeTrailingPathDelimiter(ExtractFilePath(Application.ExeName));FHistoryFile:=B+'conversation-history.json';FMemoryMap.MaxItems:=100;FMemoryMap.StoreFullPrompt:=True;FMemoryMap.StoreFullResponse:=True;FMemoryMap.DetectInformationLoss:=True;FMemoryMap.RedactSensitiveData:=True;if FileExists(FHistoryFile) then try FMemoryMap.LoadFromFile(FHistoryFile);except FMemoryMap.StartFlow('','Assistente','usuario','interface');end else FMemoryMap.StartFlow('','Assistente','usuario','interface');end;
procedure Tfrmmain.SalvarMemoria;begin if (FMemoryMap=nil) or (FHistoryFile='') then Exit;try FMemoryMap.SaveToFile(FHistoryFile);except end;end;
procedure Tfrmmain.AplicarConfiguracao;begin if (FSetMain=nil) or (FAssistantManager=nil) then Exit;FAssistantManager.ChatGPT.TOKEN:=FSetMain.CHATGPT;if (FSetMain.ChatGPTProvider>=0) and (FSetMain.ChatGPTProvider<=Ord(High(TAIProvider))) then FAssistantManager.ChatGPT.Provider:=TAIProvider(FSetMain.ChatGPTProvider) else FAssistantManager.ChatGPT.Provider:=AIP_OPENAI;FAssistantManager.ChatGPT.CustomModel:=FSetMain.ChatGPTModel;FAssistantManager.ChatGPT.URL:=FSetMain.ChatGPTURL;FJarvisClient.BaseURL:=FSetMain.JarvisURL;FJarvisClient.APIKey:=FSetMain.JarvisAPIKey;end;
procedure Tfrmmain.CarregarAvatarEstatico;var B,F:string;begin GifAvatar.Animate:=False;B:=IncludeTrailingPathDelimiter(ExtractFilePath(Application.ExeName));F:=ExpandFileName(B+'..'+PathDelim+'img'+PathDelim+'robo-start.gif');if not FileExists(F) then F:=ExpandFileName(B+'img'+PathDelim+'robo-start.gif');if FileExists(F) then begin GifAvatar.FileName:=F;GifAvatar.Visible:=True;end else GifAvatar.Visible:=False;end;
procedure Tfrmmain.SetEstado(const ATexto:string;AOcupado:Boolean);begin lblStatus.Caption:=ATexto;FAguardandoResposta:=AOcupado;btEnviar.Enabled:=not AOcupado;edPergunta.Enabled:=not AOcupado;end;
procedure Tfrmmain.EnviarPergunta;begin ProcessarEntrada(edPergunta.Text);end;
procedure Tfrmmain.ProcessarEntrada(const ATexto:string);var P,H,C:string;begin if FAguardandoResposta then Exit;P:=Trim(ATexto);if P='' then begin RetomarEscuta;Exit;end;PausarEscuta;FCurrentUserText:=P;H:=Trim(FMemoryMap.BuildConversationContext(100));if H<>'' then C:='Historico completo da conversa anterior:'+sLineBreak+H+sLineBreak+sLineBreak+'Nova fala do usuario:'+sLineBreak+P+sLineBreak+sLineBreak+'Analise a nova fala considerando todo o historico acima e responda mantendo o contexto.' else C:=P;FMemoryItem:=FMemoryMap.BeginAgentStep('Assistente',tamOrquestrador,P,H);memResposta.Lines.Add('Você: '+P);memResposta.Lines.Add('');edPergunta.Clear;SetEstado('Pensando...',True);try FAssistantManager.ProcessUserRequestAsync(C);except on E:Exception do begin if Assigned(FMemoryItem) then begin FMemoryItem.Erro:=E.Message;FMemoryMap.EndAgentStep(FMemoryItem,'Falha ao enviar pergunta',E.Message,'erro','','');SalvarMemoria;FMemoryItem:=nil;end;SetEstado('Erro. Pronto para nova tentativa',False);RetomarEscuta;end;end;end;
procedure Tfrmmain.FalarResposta(const ATexto:string);var C:TReceptionConfig;T:string;begin if (FSetMain=nil) or not FSetMain.AutoSpeak then begin RetomarEscuta;Exit;end;T:=Trim(ATexto);if T='' then begin RetomarEscuta;Exit;end;FillChar(C,SizeOf(C),0);C.Token:=FSetMain.CHATGPT;C.AudioToken:=FSetMain.VoiceAPIToken;if C.AudioToken='' then C.AudioToken:=FSetMain.CHATGPT;C.Model:=FSetMain.VoiceModel;C.URL:=FSetMain.VoiceEndpoint;C.Language:=FSetMain.VoiceLanguage;C.Voice:=FSetMain.SynthVoice;if C.Voice='' then C.Voice:=FSetMain.VoiceRemoteVoice;C.Provider:=FSetMain.VoiceProvider;C.RecogEngine:=FSetMain.RecogEngine;C.SynthEngine:=FSetMain.SynthEngine;C.Volume:=FSetMain.SynthVolume;C.Rate:=FSetMain.SynthRate;FSpeechJob:=TReceptionJob.Create(rjSpeak,C,T,'','main');end;
procedure Tfrmmain.btEnviarClick(Sender:TObject);begin EnviarPergunta;end;
procedure Tfrmmain.edPerguntaKeyDown(Sender:TObject;var Key:Word;Shift:TShiftState);begin if (Key=VK_RETURN) and (Shift=[]) then begin Key:=0;EnviarPergunta;end;end;
procedure Tfrmmain.btConfigClick(Sender:TObject);var F:TfrmConfig;begin if FAguardandoResposta then Exit;F:=TfrmConfig.Create(Self);try if F.ShowModal=mrOk then begin FSetMain.CarregaContexto;AplicarConfiguracao;if FContinuousListener.Enabled then begin FContinuousListener.Stop;IniciarEscuta;end;end;finally F.Free;end;end;
procedure Tfrmmain.OnAgentStateChange(Sender:TObject;AState:TAgentState;const ADescription:string);begin case AState of asIdle:lblStatus.Caption:='Pronto';asPlanning:lblStatus.Caption:='Analisando...';asExecutingStep:lblStatus.Caption:='Processando...';asCallingTool:lblStatus.Caption:='Executando...';asError:lblStatus.Caption:='Erro no agente';end;end;
procedure Tfrmmain.OnAgentComplete(Sender:TObject;const AResponseText,AProvider:string;ASuccess:Boolean);var T:string;begin T:=Trim(AResponseText);if T='' then if ASuccess then T:='(resposta vazia)' else T:='Não foi possível obter uma resposta.';if Assigned(FMemoryItem) then begin if not ASuccess then FMemoryItem.Erro:=T;FMemoryMap.EndAgentStep(FMemoryItem,'Nova fala analisada','Resposta produzida','responder',T,T);SalvarMemoria;FMemoryItem:=nil;end;memResposta.Lines.Add('Assistente: '+T);memResposta.Lines.Add('');SetEstado('Pronto para conversar',False);if ASuccess then FalarResposta(T) else RetomarEscuta;FCurrentUserText:='';end;
end.
